formats:
  kardex:
    processor: KardexProcessor
    columns:
      - name: "WO No"
        type: "string"
        required: true
      - name: "Open Date"
        type: "date"
        required: true
      - name: "Job Description"
        type: "string"
        required: true
      - name: "Custamt"
        type: "float"
        required: false
      - name: "ST"
        type: "string"
        required: false
      - name: "Cat"
        type: "string"
        required: false
    validations:
      required_columns: ["WO No", "Open Date", "Job Description"]
      date_format: "%Y-%m-%d"
    transformations:
      - clean_work_order
      - format_dates
      - clean_description
