fault_categories:
  Engine Core:
    keywords:
      - engine
      - cylinder
      - piston
      - compression
      - misfire
      - engine overhaul
      - head gasket
      - valve
      - manifold
      - oil seal
      - motor
    subcategories:
      Cylinder:
        keywords:
          - cylinder
          - piston
          - compression
          - misfire
      Valvetrain:
        keywords:
          - valve
          - rocker
          - camshaft
          - timing
      Seals:
        keywords:
          - oil seal
          - gasket
          - leak

  Engine Cooling:
    keywords:
      - coolant
      - radiator
      - water pump
      - overheat
      - fan belt
      - thermostat
      - temperature sensor
      - cooling system
    subcategories:
      Radiator:
        keywords:
          - radiator
          - coolant
          - leak
          - overheat
      Pump:
        keywords:
          - water pump
          - pump
          - coolant flow
      Sensors:
        keywords:
          - temperature sensor
          - thermostat
          - temp

  Engine Fuel:
    keywords:
      - fuel
      - injector
      - pump
      - tank
      - filter
      - line
      - pressure
    subcategories:
      Delivery:
        keywords:
          - pump
          - line
          - pressure
          - filter
      Injection:
        keywords:
          - injector
          - rail
          - spray
      Storage:
        keywords:
          - tank
          - gauge
          - sender
          - cap

  Engine Air:
    keywords:
      - air filter
      - pcv filter
      - turbo
      - intake
      - air flow
      - maf sensor
      - throttle body
    subcategories:
      Filtration:
        keywords:
          - air filter
          - pcv filter
          - filter element
      Intake:
        keywords:
          - intake
          - throttle body
          - manifold
      Sensors:
        keywords:
          - maf sensor
          - air flow
          - sensor
      Forced Induction:
        keywords:
          - turbo
          - supercharger
          - boost

  Engine Oil:
    keywords:
      - oil
      - lubrication
      - oil pressure
      - oil leak
      - oil filter
      - oil pump
    subcategories:
      Leaks:
        keywords:
          - oil leak
          - seepage
          - gasket
      Pressure:
        keywords:
          - oil pressure
          - pump
          - gauge
      Filtration:
        keywords:
          - oil filter
          - filter housing
          - filter change

  Engine Emissions:
    keywords:
      - emissions
      - egr
      - dpf
      - catalytic
      - oxygen sensor
      - nox
    subcategories:
      EGR System:
        keywords:
          - egr valve
          - egr cooler
          - exhaust gas
      DPF System:
        keywords:
          - dpf
          - particulate filter
          - regeneration
      Sensors:
        keywords:
          - oxygen sensor
          - nox sensor
          - lambda
      Catalytic:
        keywords:
          - catalytic converter
          - cat
          - converter

  Engine Fluids:
    keywords:
      - adblue
      - def fluid
      - diesel exhaust fluid
      - urea
    subcategories:
      AdBlue:
        keywords:
          - adblue
          - def fluid
          - diesel exhaust fluid
          - urea
          - top up adblue
          - purchase adblue

  Transmission Manual:
    keywords:
      - transmission
      - gear
      - clutch
      - gearbox
      - shifter
      - manual transmission
      - synchro
    subcategories:
      Clutch:
        keywords:
          - clutch
          - pressure plate
          - release bearing
          - flywheel
      Gearbox:
        keywords:
          - gear
          - synchro
          - gearbox
          - shifter
      Linkage:
        keywords:
          - linkage
          - shift fork
          - selector

  Transmission Auto:
    keywords:
      - automatic
      - auto transmission
      - torque converter
      - shift solenoid
      - valve body
    subcategories:
      Hydraulics:
        keywords:
          - valve body
          - solenoid
          - pressure
          - fluid
      Mechanical:
        keywords:
          - torque converter
          - planetary
          - band
      Electronics:
        keywords:
          - tcm
          - sensor
          - control module

  Drivetrain:
    keywords:
      - differential
      - drive shaft
      - axle
      - transfer case
      - cv joint
      - propeller shaft
    subcategories:
      Differential:
        keywords:
          - differential
          - diff
          - ring gear
          - pinion
      Shafts:
        keywords:
          - drive shaft
          - propeller shaft
          - cv joint
          - universal joint
      Transfer:
        keywords:
          - transfer case
          - 4wd
          - awd

  Battery System:
    keywords:
      - battery
      - charging
      - voltage
      - alternator
      - starter
      - electrical system
      - power supply
      - cranking
      - dead battery
      - battery drain
      - battery terminal
    subcategories:
      Maintenance:
        keywords:
          - battery check
          - battery replacement
          - terminal cleaning
          - battery service
          - battery test
          - battery drain
      Charging:
        keywords:
          - charging system
          - alternator
          - voltage regulator
          - charging issue
      Starting:
        keywords:
          - starter
          - cranking
          - start issue
          - starter motor

  Electrical:
    keywords:
      - electrical
      - wiring
      - fuse
      - relay

  Electrical Lighting:
    keywords:
      - light
      - headlight
      - taillight
      - bulb
      - lamp
      - lighting
    subcategories:
      Front:
        keywords:
          - headlight
          - fog light
          - high beam
          - low beam
      Rear:
        keywords:
          - taillight
          - brake light
          - reverse light
      Signals:
        keywords:
          - indicator
          - emergency light
          - hazard
          - turn signal

  Electrical Accessories:
    keywords:
      - accessory
      - radio
      - power window
      - camera
      - alarm
      - horn
    subcategories:
      Entertainment:
        keywords:
          - radio
          - speaker
          - bluetooth
          - usb
          - audio
      Windows:
        keywords:
          - power window
          - window motor
          - window switch
      Safety:
        keywords:
          - camera
          - reverse sensor
          - alarm
          - horn
      Instruments:
        keywords:
          - gauge
          - meter
          - display
          - cluster

  Electronics:
    keywords:
      - ecu
      - sensor
      - module
      - computer
      - diagnostic
      - scanner
      - circuit
      - wire
      - connector
    subcategories:
      Sensors:
        keywords:
          - sensor
          - probe
          - reading
      Modules:
        keywords:
          - module
          - ecu
          - computer
          - control unit
      Communication:
        keywords:
          - can bus
          - network
          - diagnostic
      Wiring:
        keywords:
          - circuit
          - wire
          - harness
          - connector
          - switch

  HVAC:
    keywords:
      - ac
      - a/c
      - air con
      - air conditioning
      - cooling
      - freezer
      - refrigerant
      - compressor
      - condenser
      - evaporator
      - blower
      - fan
      - ventilation
      - heater
      - suction hose
      - discharge hose
      - gas
    subcategories:
      Cooling:
        keywords:
          - ac
          - a/c
          - air con
          - cooling
          - freezer
          - refrigerant
          - gas
          - compressor
          - condenser
          - evaporator
          - suction hose
          - discharge hose
      Ventilation:
        keywords:
          - blower
          - fan
          - ventilation
          - duct
      Heating:
        keywords:
          - heater
          - heat
          - warm

  Exhaust:
    keywords:
      - exhaust
      - muffler
      - catalytic
      - pipe
      - manifold
      - emission
    subcategories:
      Emissions:
        keywords:
          - catalytic
          - converter
          - oxygen sensor
          - emission
      Sound:
        keywords:
          - muffler
          - resonator
          - noise
      Piping:
        keywords:
          - pipe
          - manifold
          - leak
          - mount

  Brakes:
    keywords:
      - brake
      - rotor
      - caliper
      - pad
      - abs
      - master cylinder
    subcategories:
      Hydraulics:
        keywords:
          - master cylinder
          - brake line
          - fluid
          - bleeding
      Mechanical:
        keywords:
          - pad
          - rotor
          - caliper
          - shoe
      Electronics:
        keywords:
          - abs
          - sensor
          - module

  Suspension:
    keywords:
      - suspension
      - shock
      - strut
      - spring
      - bushing
      - control arm
      - stabilizer
    subcategories:
      Springs:
        keywords:
          - spring
          - coil
          - leaf
          - sag
      Dampers:
        keywords:
          - shock
          - strut
          - absorber
      Bushings:
        keywords:
          - bushing
          - mount
          - rubber
          - control arm

  Steering:
    keywords:
      - steering
      - rack
      - power steering
      - tie rod
      - ball joint
      - column
    subcategories:
      Power System:
        keywords:
          - power steering
          - pump
          - fluid
          - assist
      Mechanical:
        keywords:
          - rack
          - pinion
          - tie rod
          - ball joint
      Column:
        keywords:
          - column
          - shaft
          - u-joint

  Wheels:
    keywords:
      - wheel
      - tire
      - tyre
      - alignment
      - balance
      - bearing
      - rim
      - austone
      - radial
      - bald
    subcategories:
      Tires:
        keywords:
          - tire
          - tyre
          - austone
          - radial
          - bald
          - flat
          - puncture
      Alignment:
        keywords:
          - alignment
          - tracking
          - balance
      Bearings:
        keywords:
          - bearing
          - hub

  Body External:
    keywords:
      - body
      - panel
      - bumper
      - fender
      - door
      - paint
      - dent
      - scratch
      - sticker
      - logo
      - rust
      - rust-proofing
      - syntech
      - rain cover
    subcategories:
      Panels:
        keywords:
          - panel
          - bumper
          - fender
          - door
          - dent
          - scratch
      Paint:
        keywords:
          - paint
          - repaint
          - touch up
          - color
      Protection:
        keywords:
          - rust
          - rust-proofing
          - syntech
          - rain cover
          - cover
      Branding:
        keywords:
          - sticker
          - logo
          - die-cut
          - print-cut
          - everbeauty
          - company design

  Body Internal:
    keywords:
      - interior
      - cabin
      - dashboard
      - seat
      - upholstery
      - trim
      - panel
      - console
      - compartment
      - storage
      - floor
    subcategories:
      Seats:
        keywords:
          - seat
          - cushion
          - upholstery
          - seat belt
          - seat adjustment
          - seat frame
      Dashboard:
        keywords:
          - dashboard
          - instrument panel
          - console
          - gauge cluster
      Storage:
        keywords:
          - storage compartment
          - glove box
          - console box
          - cargo area
      Trim:
        keywords:
          - trim panel
          - interior panel
          - headliner
          - carpet
          - floor mat

  Modifications:
    keywords:
      - modify
      - modification
      - extension
      - chassis extension
      - width extension
      - wong fong
    subcategories:
      Chassis:
        keywords:
          - chassis extension
          - extend chassis
          - chassis width
          - wong fong
      Body:
        keywords:
          - body modification
          - width extension
          - extend width

  Maintenance:
    keywords:
      - service
      - maintenance
      - inspection
      - no job done
      - cancel
      - cancelled
      - refer
      - quotation
    subcategories:
      Inspection:
        keywords:
          - inspection
          - check
          - diagnose
      Fluids:
        keywords:
          - fluid
          - oil
          - coolant
      Administrative:
        keywords:
          - no job done
          - cancel
          - cancelled
          - refer
          - quotation

  Safety:
    keywords:
      - airbag
      - seatbelt
      - safety
      - warning
      - crash
      - restraint
    subcategories:
      Airbags:
        keywords:
          - airbag
          - srs
          - deployment
          - module
      Seatbelts:
        keywords:
          - seatbelt
          - pretensioner
          - buckle
      Warning Systems:
        keywords:
          - warning
          - sensor
          - light
          - alarm
