# Goldbell Leasing ChatGPT Prompts
# Author: Chris Yeo

# System prompts define the AI's role and behavior
system_prompts:
  default: |
    You are an AI assistant for Goldbell Leasing, specializing in vehicle maintenance and fault category analysis.
    You should provide clear, concise responses focused on vehicle maintenance, repairs, and fault category diagnosis.
    Always maintain a professional tone and use industry-standard terminology.
    When discussing detailed fault information, always refer to them as fault sub-categories rather than fault details.

  maintenance_expert: |
    You are a vehicle maintenance expert with deep knowledge of commercial vehicle repairs.
    Focus on practical solutions and preventive maintenance recommendations.
    Use technical terms but explain them when necessary.
    When discussing issues, always refer to them as fault categories rather than just faults.
    For detailed fault information, use the term fault sub-categories rather than fault details.

  response_processor: |
    You are a professional vehicle maintenance analyst. Your role is to:
    1. Present data analysis results in a clear, concise manner
    2. Focus only on facts present in the raw response
    3. Use professional but straightforward language
    4. Avoid adding speculation or information not present in the raw data
    5. Keep responses brief and to the point
    6. Never format as an email or letter

# Analysis prompts for different types of fault analysis
analysis_prompts:
  fault_categorization: |
    Analyze the following fault description and categorize it based on our predefined fault categories and their sub-categories:
    Description: {description}
    
    Provide:
    1. Main fault category
    2. Sub-category (if applicable)
    3. Confidence level of categorization
    4. Any additional relevant observations

  maintenance_recommendation: |
    Based on the following vehicle fault history:
    {fault_history}
    Provide maintenance recommendations and potential preventive measures.
    Consider:
    1. Immediate actions needed
    2. Preventive maintenance steps
    3. Long-term recommendations

  cost_analysis: |
    For the following repair details:
    Work Order: {wo_details}
    Analyze:
    1. Cost effectiveness of the repair
    2. Alternative approaches if any
    3. Preventive measures to reduce future costs

# Query templates for common user interactions
query_templates:
  vehicle_history: |
    Analyze the maintenance history for vehicle {vehicle_id}:
    {history_data}
    Provide:
    1. Common issues identified
    2. Maintenance patterns
    3. Areas of concern

  fault_pattern: |
    Review the following fault patterns:
    {fault_data}
    Identify:
    1. Recurring issues
    2. Root causes
    3. Recommended solutions

  repair_validation: |
    Review this repair approach:
    {repair_details}
    Validate:
    1. Appropriateness of repair method
    2. Completeness of solution
    3. Additional recommendations

# Response formatting templates
response_formats:
  standard_analysis: |
    Analysis Summary:
    {summary}
    
    Key Findings:
    {findings}
    
    Recommendations:
    {recommendations}

  quick_response: |
    Category: {category}
    Issue: {issue}
    Solution: {solution}

  detailed_report: |
    Technical Analysis Report
    ------------------------
    Problem Description: {problem}
    Root Cause Analysis: {analysis}
    Recommended Actions: {actions}
    Preventive Measures: {prevention}
    Additional Notes: {notes}

  enhance_response: |
    Original query: {query}
    Raw response: {raw_response}

    Rewrite this response to be:
    1. Professional and concise
    2. Focused only on facts from the raw response
    3. Clear and straightforward
    4. Free of speculation or added information

  error_response: |
    We encountered an issue while processing your request:
    Error: {error_message}
    Please try again or rephrase your query.
