# Goldbell Leasing ChatGPT Prompts
# Author: Chris Yeo

# System prompts define the AI's role and behavior
system_prompts:
  default: |
    You are an AI assistant for Goldbell Leasing, specializing in vehicle maintenance and fault category analysis.
    You should provide clear, concise responses focused on vehicle maintenance, repairs, and fault category diagnosis.
    Always maintain a professional tone and use industry-standard terminology.
    When discussing detailed fault information, always refer to them as fault sub-categories rather than fault details.

  maintenance_expert: |
    You are a vehicle maintenance expert with deep knowledge of commercial vehicle repairs.
    Focus on practical solutions and preventive maintenance recommendations.
    Use technical terms but explain them when necessary.
    When discussing issues, always refer to them as fault categories rather than just faults.
    For detailed fault information, use the term fault sub-categories rather than fault details.

# Fault category mappings and keywords
fault_categories:
  engine:
    name: "Engine"
    keywords:
      - "engine"
      - "motor"
      - "overheating"
      - "coolant"
      - "oil leak"
      - "fuel"
      - "overheat"
      - "dpf"
      - "engine oil"
      - "adblue"
      - "timing belt"
    sub_categories:
      cooling:
        name: "Cooling System"
        keywords: ["overheating", "coolant leak", "radiator", "thermostat", "overheat", "coolant", "water leak"]
      fuel:
        name: "Fuel System"
        keywords: ["fuel pump", "injector", "fuel leak", "fuel filter", "adblue", "dpf"]
      lubrication:
        name: "Lubrication System"
        keywords: ["oil leak", "oil pressure", "oil filter", "oil consumption", "engine oil", "oil level"]
      mechanical:
        name: "Mechanical"
        keywords: ["knocking", "timing", "compression", "bearing", "timing belt", "belt"]
  transmission:
    name: "Transmission"
    keywords:
      - "transmission"
      - "gearbox"
      - "clutch"
      - "gear shift"
      - "gear"
      - "shifting"
      - "drive shaft"
      - "gear oil"
    sub_categories:
      gearbox:
        name: "Gearbox"
        keywords: ["gear noise", "gear slip", "synchronizer", "selector", "shifting", "gear", "noise when shifting", "gear oil"]
      clutch:
        name: "Clutch System"
        keywords: ["clutch slip", "clutch noise", "release bearing", "pressure plate", "clutch pedal", "clutch high"]
      drive:
        name: "Drive System"
        keywords: ["drive shaft", "cv joint", "differential", "axle", "drive line"]
  electrical:
    name: "Electrical"
    keywords:
      - "electrical"
      - "wiring"
      - "sensor"
      - "reverse sensor"
      - "light"
      - "bulb"
      - "fuse"
      - "ecu"
      - "control unit"
      - "electronic"
    sub_categories:
      lighting:
        name: "Lighting System"
        keywords: ["headlight", "tail light", "indicator", "fuse", "bulb", "light", "signal", "brake light"]
      electronics:
        name: "Electronics"
        keywords: ["sensor", "control unit", "wiring", "computer", "reverse sensor", "camera", "iu", "electronic", "ecu", "dashboard", "instrument"]
      wiring:
        name: "Wiring System"
        keywords: ["wiring", "wire", "short circuit", "connection", "harness", "electrical fault"]
  battery:
    name: "Battery"
    keywords:
      - "battery"
      - "charging"
      - "not charging"
      - "alternator"
      - "starter"
      - "jump start"
      - "battery burst"
      - "battery drain"
      - "battery dead"
      - "battery weak"
      - "battery terminal"
      - "battery voltage"
    sub_categories:
      failures:
        name: "Battery Failures"
        keywords: ["battery dead", "cannot start", "hard to start", "battery burst", "battery drain", "battery weak", "battery failure"]
      related_systems:
        name: "Battery-Related Systems"
        keywords: ["starter", "alternator", "electrical drain", "multiple battery", "starter motor", "charging system"]
      services:
        name: "Battery Services"
        keywords: ["battery check", "battery terminal", "jump start", "voltage test", "battery replacement", "battery charging", "jumpstart"]
      component_impact:
        name: "Battery Impact on Components"
        keywords: ["tailgate operation", "ecu", "control unit", "dashboard", "instrument cluster", "vehicle lighting"]
  brakes:
    name: "Brakes"
    keywords:
      - "brake"
      - "abs"
      - "brake pad"
      - "brake fluid"
      - "pedal"
      - "soft"
      - "brake disc"
      - "brake shoe"
    sub_categories:
      hydraulic:
        name: "Hydraulic System"
        keywords: ["brake fluid", "master cylinder", "brake line", "caliper", "pedal soft", "fluid leak", "brake oil"]
      mechanical:
        name: "Mechanical Components"
        keywords: ["brake pad", "brake disc", "drum brake", "shoe", "brake shoe", "brake drum"]
      abs:
        name: "ABS System"
        keywords: ["abs sensor", "abs module", "abs pump", "abs ring", "abs light"]
  suspension:
    name: "Suspension"
    keywords:
      - "suspension"
      - "shock absorber"
      - "spring"
      - "steering"
      - "alignment"
      - "wheel"
      - "ball joint"
      - "bushing"
    sub_categories:
      damping:
        name: "Damping System"
        keywords: ["shock absorber", "strut", "damper", "absorber"]
      springs:
        name: "Springs"
        keywords: ["coil spring", "leaf spring", "air suspension", "spring"]
      steering:
        name: "Steering System"
        keywords: ["power steering", "steering rack", "tie rod", "ball joint", "steering wheel"]
      alignment:
        name: "Wheel Alignment"
        keywords: ["alignment", "camber", "toe", "caster", "wheel alignment"]
  body:
    name: "Body"
    keywords:
      - "body"
      - "paint"
      - "rust"
      - "dent"
      - "door"
      - "window"
      - "box"
      - "tailgate"
      - "mudflap"
    sub_categories:
      exterior:
        name: "Exterior"
        keywords: ["paint", "rust", "dent", "scratch", "mudflap", "mud flap"]
      structural:
        name: "Structural"
        keywords: ["frame", "chassis", "mount", "crossmember", "box", "cargo"]
      accessories:
        name: "Accessories"
        keywords: ["door", "window", "mirror", "wiper", "tailgate", "step", "foot step"]
  tires:
    name: "Tires"
    keywords:
      - "tyre"
      - "tire"
      - "wheel"
      - "puncture"
      - "flat"
      - "patching"
      - "rotation"
    sub_categories:
      replacement:
        name: "Tire Replacement"
        keywords: ["new tyre", "new tire", "replace tyre", "replace tire", "tyre bald", "tire bald"]
      repair:
        name: "Tire Repair"
        keywords: ["patch", "puncture", "flat", "leak", "patching"]
      maintenance:
        name: "Tire Maintenance"
        keywords: ["rotation", "pressure", "balance", "swap", "rotate"]
  maintenance:
    name: "Maintenance"
    keywords:
      - "service"
      - "maintenance"
      - "inspection"
      - "routine"
      - "lta"
      - "iu"
      - "general inspection"
      - "servicing"
    sub_categories:
      scheduled:
        name: "Scheduled Service"
        keywords: ["regular service", "interval service", "maintenance schedule", "general inspection", "servicing"]
      preventive:
        name: "Preventive Maintenance"
        keywords: ["inspection", "adjustment", "lubrication", "lta", "iu", "vicom"]
      repair:
        name: "Repair Work"
        keywords: ["repair", "replacement", "overhaul", "fix"]

# Analysis prompts for different types of fault analysis
analysis_prompts:
  fault_categorization: |
    Analyze the following fault description and categorize it based on our predefined fault categories and their sub-categories:
    Description: {description}
    
    Consider the main fault categories and their sub-categories:
    1. Engine:
       - Cooling System (sub-category): overheating, coolant issues
       - Fuel System (sub-category): fuel delivery, injection
       - Lubrication (sub-category): oil-related issues
       - Mechanical (sub-category): internal engine problems
    2. Transmission:
       - Gearbox (sub-category): gear-related issues
       - Clutch System (sub-category): clutch operation
       - Drive System (sub-category): driveline components
    3. Electrical:
       - Lighting (sub-category): lights, indicators
       - Electronics (sub-category): sensors, control units
       - Wiring (sub-category): wiring, electrical connections
    4. Battery:
       - Failures (sub-category): battery-related issues
       - Related Systems (sub-category): starter, alternator
       - Services (sub-category): battery checks, jump starts
       - Component Impact (sub-category): impact on other components
    5. Brakes:
       - Hydraulic System (sub-category): fluid, lines
       - Mechanical Components (sub-category): pads, discs
       - ABS System (sub-category): anti-lock system
    6. Suspension:
       - Damping System (sub-category): shock absorbers
       - Springs (sub-category): suspension springs
       - Steering (sub-category): steering components
       - Wheel Alignment (sub-category): alignment issues
    7. Body:
       - Exterior (sub-category): paint, cosmetic
       - Structural (sub-category): frame, chassis
       - Accessories (sub-category): doors, windows
    8. Tires:
       - Tire Replacement (sub-category): new tire installation
       - Tire Repair (sub-category): patching, fixing
       - Tire Maintenance (sub-category): rotation, pressure
    9. Maintenance:
       - Scheduled Service (sub-category): regular maintenance
       - Preventive Maintenance (sub-category): proactive care
       - Repair Work (sub-category): fixes and overhauls
    
    Provide:
    1. Main fault category
    2. Sub-category (if applicable)
    3. Confidence level (High/Medium/Low)
    4. Reasoning for categorization

  maintenance_recommendation: |
    Based on the following vehicle fault history:
    {fault_history}
    Provide maintenance recommendations and potential preventive measures.
    Consider:
    1. Immediate actions needed
    2. Preventive maintenance steps
    3. Long-term recommendations

  cost_analysis: |
    For the following repair details:
    Work Order: {wo_details}
    Analyze:
    1. Cost effectiveness of the repair
    2. Alternative approaches if any
    3. Preventive measures to reduce future costs

# Query templates for common user interactions
query_templates:
  vehicle_history: |
    Analyze the maintenance history for vehicle {vehicle_id}:
    {history_data}
    Provide:
    1. Common issues identified
    2. Maintenance patterns
    3. Areas of concern

  fault_pattern: |
    Review the following fault patterns:
    {fault_data}
    Identify:
    1. Recurring issues
    2. Root causes
    3. Recommended solutions

  repair_validation: |
    Review this repair approach:
    {repair_details}
    Validate:
    1. Appropriateness of repair method
    2. Completeness of solution
    3. Additional recommendations

# Response formatting templates
response_formats:
  standard_analysis: |
    Analysis Summary:
    {summary}
    
    Key Findings:
    {findings}
    
    Recommendations:
    {recommendations}

  quick_response: |
    Category: {category}
    Issue: {issue}
    Solution: {solution}

  detailed_report: |
    Technical Analysis Report
    ------------------------
    Problem Description: {problem}
    Root Cause Analysis: {analysis}
    Recommended Actions: {actions}
    Preventive Measures: {prevention}
    Additional Notes: {notes}
